name: Python CI

on:
  push:
    branches: [main, master]      # Trigger on push to main or master
  pull_request:                   # Trigger on pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   # Checkout repository code

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'    # Use Python 3.13

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies with pipenv
      run: |
        pipenv install --dev

    - name: Run unit tests
      run: |
        pipenv run python -m unittest discover -s test
